spring:
  profiles:
    include:
      - config
  application:
    name: qlik-to-sharepoint

logging:
  charset:
    console: UTF-8
  pattern:
    console: "%d{dd.MM.yyyy HH:mm:ss.SSSXXX} %highlight(%-5level) %logger{0} - %msg%n"
  level:
    root: INFO
    no.fintlabs: INFO
    com.azure: WARN
    com.microsoft: WARN
    org.apache: WARN
    org.springframework.web.servlet.DispatcherServlet: WARN