apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: novari-qlik-sharepoint-sync
  labels:
    app.kubernetes.io/name: novari-qlik-sharepoint-sync
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: novari-qlik-sharepoint-sync
    app.kubernetes.io/part-of: fintlabs-no
    fintlabs.no/team: analyse
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8080
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/novari-qlik-sharepoint-sync
  imagePullPolicy: Always
  imagePullSecrets: 
    - ghcr
  replicas: 1
  resources:
    limits:
      memory: "1024Mi"
      cpu: "500m"
    requests:
      memory: "320Mi"
      cpu: "100m"
  probes:
    readiness:
      path: /actuator/health
      port: 8080
  env: []
  envFrom:
    - secretRef:
        name: novari-qlik-sharepoint-sync