apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: novari-qlik-sharepoint-sync
  labels:
    app.kubernetes.io/name: novari-qlik-sharepoint-sync
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: novari-qlik-sharepoint-sync
    app.kubernetes.io/part-of: qlik
    fintlabs.no/team: analyse
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8080
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/novari-qlik-sharepoint-sync
  imagePullPolicy: Always
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  resources:
    limits:
      memory: "1024Mi"
      cpu: "500m"
    requests:
      memory: "320Mi"
      cpu: "100m"
  env: []
  envFrom:
    - secretRef:
        name: novari-qlik-sharepoint-sync